### ISSUE TITLE
Error setting up MDNS responder

### ISSUE THREAD

**Issue by HuguesT** [redgick/Redgick_Laboite#3]
Bonjour ,

J'ai un ESP32 Adafruit Feather et j'ai suivi le tutoriel qui est disponible ici :  https://github.com/laboiteproject/laboite-maker/wiki/Assembly-instructions

Mais, au démarrage j'ai une erreur "Error setting up MDNS responder!"

Est-ce que ce tuto est toujours d'actualité ? 

Si non, est-ce qu'il est possible de réaliser une boite avec un ESP32 au lieu d'un ESP8266 ? 

Merci !

**Comment by bgaultier** [comment]
Bonjour @HuguesT,

Nous vous recommandons plutôt de suivre le [tutoriel suivant](https://docs.lenuage.io/hardware/laboite_maker/assembly_instructions/#1-creation-dun-compte-sur-lenuageio), adapté au microcontrôleur ESP32.

Bon courage 👍 

—Baptiste
